name: Continuous Integration
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  DOTNET_VERSION: 8.0.x
  PROJECT_NAME: Kursa4Crypto.Cli
  PROJECT_PATH: $PROJECT_NAME/$PROJECT_NAME.csproj
jobs:
  build-win64:
    name: Build Windows x64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: $DOTNET_VERSION
      - name: Build
        run: dotnet build -c Release
      - name: Publish
        run: dotnet publish $PROJECT_PATH -c Release -o publish -r win-x64
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: $PROJECT_NAME-win64
          path: publish
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: $DOTNET_VERSION
      - name: Build
        run: dotnet build -c Release
      - name: Publish
        run: dotnet publish $PROJECT_PATH -c Release -o publish -r linux-x64
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: $PROJECT_NAME-linux64
          path: publish