name: Build Release Artifacts

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Version Bump
        run: sed -Ei "s|<VersionPrefix>[0-9]*\.[0-9]*\.[0-9]*</VersionPrefix>|<VersionPrefix>${GITHUB_REF_NAME:1}</VersionPrefix>|g" Kursa4Crypto.Cli/Kursa4Crypto.Cli.csproj

      - name: Build
        run: dotnet build -c Release
      
      - name: Publish Win64
        run: dotnet publish Kursa4Crypto.Cli/Kursa4Crypto.Cli.csproj -c Release -o publish-win64 -r win-x64
      - name: Upload Win64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kursa4Crypto.Cli-win64
          path: publish-win64

      - name: Publish Linux64
        run: dotnet publish Kursa4Crypto.Cli/Kursa4Crypto.Cli.csproj -c Release -o publish-linux64 -r linux-x64
      - name: Upload Linux64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kursa4Crypto.Cli-linux64
          path: publish-linux64
